version: "3.9"

services:
  # MySQL Database
  mysql:
    image: mysql:8
    container_name: oms_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis
  redis:
    image: redis:7-alpine
    container_name: oms_redis
    ports:
      - "6379:6379"

  # API Gateway backend (handles auth, products, orders)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oms_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
